### ISSUE TITLE
Conceitual Error: AsyncStorage keep strings not objects

### ISSUE THREAD

**Issue by aristofanio** [abhi4pr/react-native-app#1]
You is recovering user from AsyncStorage as object, but user is um stringified JSON. 
This is not work!

```
async componentDidMount() {
      let getValue = await AsyncStorage.getItem('user');
       this.setState({ getValue });        
}
```

Try:

```
componentDidMount() {
    AsyncStorage.getItem('user').then(value => {
      this.setState({ getValue: JSON.parse(value) }); //read like a stringified JSON
    });
 }
```

**Comment by abhi4pr** [comment]
object are not valid as a react child (found: object with keys {id,uname,uemail,upass}). if you meant to render a collection of children, use array instead

**Comment by aristofanio** [comment]
Hi!
Suggestion: you need to study more about REST, JSON and JS. Your difficult is in conceptual statments.
Please, check this image:
<img width="963" alt="Screen Shot 2019-09-04 at 11 00 36" src="https://user-images.githubusercontent.com/250065/64261971-c47eb300-cf03-11e9-9621-c1c8977c96b5.png">
